version: "3.9"
services:
  dog_trainer:
    build: .
    ports:
      - "7070:7070"
    depends_on:
      - "rethinkdb"
      - "rabbitmq"
  rethinkdb:
    image: "rethinkdb"
    ports:
      - "8080:8080"
  rabbitmq:
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_VHOST=dog
    ports:
      - "15672:15672"
  nginx:
    image: "nginx"
    depends_on:
      - "dog_trainer"
