-module(dog_api_router).

-include("dog_trainer.hrl").

-export([start_link/0]).

start_link() ->
    Dispatch = cowboy_router:compile([
        {'_', [
            {"/api/external", api_handler, #{}},
            {"/api/external/:id", api_handler, #{}},
            {"/api/external/:id/:sub", api_handler, #{}},
            {"/api/externals", plural_api_handler, #{}},
            {"/api/externals/:sub", plural_api_handler, #{}},
            {"/api/V2/external", api_handler_v2, #{}},
            {"/api/V2/external/:id", api_handler_v2, #{}},
            {"/api/V2/external/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/externals", plural_api_handler_v2, #{}},
            {"/api/V2/externals/:sub", plural_api_handler_v2, #{}},
            {"/api/V2/file_transfer/:id", dog_file_transfer_api_v2, #{}},
            {"/api/V2/external/:id", plural_api_handler_v2, #{}},
            {"/api/group", api_handler, #{}},
            {"/api/group/:id", api_handler, #{}},
            {"/api/group/:id/:sub", api_handler, #{}},
            {"/api/groups", plural_api_handler, #{}},
            {"/api/groups/:sub", plural_api_handler, #{}},
            {"/api/group", api_handler, #{}},
            {"/api/group/:id", api_handler, #{}},
            {"/api/group/:id/:sub", api_handler, #{}},
            {"/api/groups", plural_api_handler, #{}},
            {"/api/groups/:sub", plural_api_handler, #{}},
            {"/api/V2/ipsets", plural_api_handler_v2, #{}},
            {"/api/V2/group", api_handler_v2, #{}},
            {"/api/V2/group/:id", api_handler_v2, #{}},
            {"/api/V2/group/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/groups", plural_api_handler_v2, #{}},
            {"/api/V2/groups/:sub", plural_api_handler_v2, #{}},
            {"/api/V2/group", api_handler_v2, #{}},
            {"/api/V2/group/:id", api_handler_v2, #{}},
            {"/api/V2/group/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/groups", plural_api_handler_v2, #{}},
            {"/api/V2/groups/:sub", plural_api_handler_v2, #{}},
            {"/api/healthcheck", healthcheck_api_handler, #{}},
            {"/api/V2/host", api_handler_v2, #{}},
            {"/api/V2/host/:id", api_handler_v2, #{}},
            {"/api/V2/host/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/hosts", plural_api_handler_v2, #{}},
            {"/api/V2/hosts/:sub", plural_api_handler_v2, #{}},
            {"/api/V2/hosts/ips", plural_api_handler_v2, #{}},
            {"/api/host", api_handler, #{}},
            {"/api/host/:id", api_handler, #{}},
            {"/api/host/:id/:sub", api_handler, #{}},
            {"/api/hosts", plural_api_handler, #{}},
            {"/api/hosts/:sub", plural_api_handler, #{}},
            {"/api/hosts/ips", plural_api_handler, #{}},
            {"/api/link", api_handler, #{}},
            {"/api/link/:id", api_handler, #{}},
            {"/api/link/:id/:sub", api_handler, #{}},
            {"/api/links", plural_api_handler, #{}},
            {"/api/links/:sub", plural_api_handler, #{}},
            {"/api/V2/link", api_handler_v2, #{}},
            {"/api/V2/link/:id", api_handler_v2, #{}},
            {"/api/V2/link/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/links", plural_api_handler_v2, #{}},
            {"/api/V2/links/:sub", plural_api_handler_v2, #{}},
            {"/api/profile", api_handler, #{}},
            {"/api/profile/:id", api_handler, #{}},
            {"/api/profile/:id/:sub", api_handler, #{}},
            {"/api/profiles", plural_api_handler, #{}},
            {"/api/profiles/:sub", plural_api_handler, #{}},
            {"/api/V2/profile", api_handler_v2, #{}},
            {"/api/V2/profile/:id", api_handler_v2, #{}},
            {"/api/V2/profile/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/profiles", plural_api_handler_v2, #{}},
            {"/api/V2/profiles/:sub", plural_api_handler_v2, #{}},
            {"/api/ruleset", api_handler, #{}},
            {"/api/ruleset/:id", api_handler, #{}},
            {"/api/ruleset/:id/:sub", api_handler, #{}},
            {"/api/rulesets", plural_api_handler, #{}},
            {"/api/rulesets/:sub", plural_api_handler, #{}},
            {"/api/V2/ruleset", api_handler_v2, #{}},
            {"/api/V2/ruleset/:id", api_handler_v2, #{}},
            {"/api/V2/ruleset/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/rulesets", plural_api_handler_v2, #{}},
            {"/api/V2/rulesets/:sub", plural_api_handler_v2, #{}},
            {"/api/publish", publish_api_handler, #{}},
            {"/api/service", api_handler, #{}},
            {"/api/service/:id", api_handler, #{}},
            {"/api/service/:id/:sub", api_handler, #{}},
            {"/api/services", plural_api_handler, #{}},
            {"/api/services/:sub", plural_api_handler, #{}},
            {"/api/V2/service", api_handler_v2, #{}},
            {"/api/V2/service/:id", api_handler_v2, #{}},
            {"/api/V2/service/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/services", plural_api_handler_v2, #{}},
            {"/api/V2/services/:sub", plural_api_handler_v2, #{}},
            {"/api/zone/", api_handler, #{}},
            {"/api/zone/:id", api_handler, #{}},
            {"/api/zone/:id/:sub", api_handler, #{}},
            {"/api/zones", plural_api_handler, #{}},
            {"/api/zones/:sub", plural_api_handler, #{}},
            {"/api/zones/ips", plural_api_handler, #{}},
            {"/api/V2/zone/", api_handler_v2, #{}},
            {"/api/V2/zone/:id", api_handler_v2, #{}},
            {"/api/V2/zone/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/zones", plural_api_handler_v2, #{}},
            {"/api/V2/zones/:sub", plural_api_handler_v2, #{}},
            {"/api/V2/zones/ips", plural_api_handler_v2, #{}},
            {"/api/fact", api_handler, #{}},
            {"/api/fact/:id", api_handler, #{}},
            {"/api/fact/:id/:sub", api_handler, #{}},
            {"/api/facts", plural_api_handler, #{}},
            {"/api/facts/:sub", plural_api_handler, #{}},
            {"/api/V2/fact", api_handler_v2, #{}},
            {"/api/V2/fact/:id", api_handler_v2, #{}},
            {"/api/V2/fact/:id/:sub", api_handler_v2, #{}},
            {"/api/V2/facts", plural_api_handler_v2, #{}},
            {"/api/V2/facts/:sub", plural_api_handler_v2, #{}}
        ]}
    ]),
    {ok, _} = cowboy:start_clear(
        http,
        [{port, 7070}, {ip, {0, 0, 0, 0}}],
        #{env => #{dispatch => Dispatch}}
    ),
    dog_api_sup:start_link().
